### ISSUE TITLE
Add possibility of specifying target block when doing a constantCall

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/Tronj#4]
In Ethereum's Web3j, it's possible to execute a constant contract call against the state of the chain at a specific block height:

```kotlin
val request = ethCall(
    Transaction.createEthCallTransaction(from, to, function), 
    DefaultBlockParameter.valueOf(BigInteger("10000000"))
)
```

I could not find a similar feature in this library, is it possible to implement it?

**Comment by Starsakary** [comment]
Yes, we will note the request and implement this in the next release.

Please be noted, Tronj is still in the testing phase and there is not yet a stable release version.

**Comment by Starsakary** [comment]
I should say currently we cannot implement this feature. We'll keep on looking java-tron's updates.
