### ISSUE TITLE
Broadcast transaction error multiple times

### ISSUE THREAD

**Issue by dericklau3** [tronprotocol/Tronj#9]
`java.lang.RuntimeException: OTHER_ERROR, <ByteString@lacaalef size=0 contents="">
    at org.tron.tronj.client.TronClient.broadcastTransaction(TronClient.java:252)`

One account calls multiple contracts, and broadcast transactions are easy to report errors

**Comment by Starsakary** [comment]
The description of the error is shown in the log of the node. Check the log if you're running a node yourself.
